[phases.setup]
nixPkgs = ["python39", "gcc", "pkg-config", "stdenv.cc.cc.lib"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed successfully'"]

[start]
cmd = "python main.py"

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
PORT = "5001"